name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install --upgrade meson meson-python
          python -m pip install -r requirements.txt

      - name: Build
        run: |
          flet pack main.py --name counter --icon icon.png --product-name table --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

      - name: Package MacOS
        if: matrix.os == 'macos-latest'
        run: |
          tar -czvf counter-macos.tar.gz -C dist counter.app

      - name: Package Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czvf counter-linux.tar.gz -C dist counter

      - name: Package Windows
        if: matrix.os == 'windows-latest'
        run: |
          7z a counter-windows.zip dist\*.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: counter
          path: |
            counter-macos.tar.gz
            counter-linux.tar.gz
            counter-windows.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: counter
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (MacOS)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./counter-macos.tar.gz
          asset_name: counter-macos.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./counter-linux.tar.gz
          asset_name: counter-linux.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./counter-windows.zip
          asset_name: counter-windows.zip
          asset_content_type: application/zip